apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: vite-social-media
  name: vite-social-media
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vite-social-media
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/social-media-vite-default: "true"
        io.kompose.service: vite-social-media
    spec:
      containers:
        - env:
            - name: VITE_BASE_URL
              value: http://172.25.248.11:8002
            - name: VITE_SOCKET_URL
              value: http://172.25.248.11:8001
          image: lamthinhphat2001/vite-social-media
          name: vite-social-media
          ports:
            - containerPort: 5173
              hostPort: 5173
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
