apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: vite-social-media
  name: vite-social-media
spec:
  ports:
    - name: "5173"
      port: 5173
      targetPort: 5173
  externalIPs:
    - '172.25.248.11'
  selector:
    io.kompose.service: vite-social-media
status:
  loadBalancer: {}
